**Name : Samruddhi Gawade**

**Roll No : 23102C0084**

**Branch : CMPN[C]**

**Sub : R Programming**

## Lecture 26 — Sequences

A **sequence** is a set of related numbers/items that follow each other in a particular order.

### 1.1 Continuous sequences with constant unit increment using `:`

In [ ]:
1:10
10:1
5:15
15:5

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [ ]:
-1:-10
-10:-1
-5:-15
-15:-5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

### 1.2 Sequences with decimal (fractional) start values

In [ ]:
1.23:10
1.23:10.54
10.54:2.23

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [ ]:
-1.23:-10
-5.23:6

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

### 1.3 The `seq()` function

```
seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)), length.out = NULL, along.with = NULL, ...)
```

In [ ]:
help(seq)

In [ ]:
seq(10)
seq(1:10)   # same as seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

### 1.4 Sequences with a predefined variable and constant increment

In [ ]:
x = 2
seq(1, x, x/10)

x = 50
seq(0, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

 [1]  0  5 10 15 20 25 30 35 40 45 50

### 1.5 Storing the outcome of sequences

In [ ]:
x = seq(1, 50, 1/2)
x

y = 2*x
y

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

### 1.6 Sequences: Index vector

Using `seq(along = x)` to build an index vector, then accessing elements through it.

In [ ]:
x = c(9,8,7,6)
ind = seq(along = x)
ind

# Accessing an element through the index vector
x[ ind[2] ]

[1] 1 2 3 4

[1] 8

### 1.7 Generating current time and date

In [ ]:
Sys.time()
Sys.Date()

[1] "2026-09-03 10:39:44 UTC"

[1] "2026-09-03"

## Lecture 27 — Sequences of Dates and Alphabets

### 2.1 `seq()` for dates
```
seq(from, to, by, length.out = NULL, along.with = NULL, ...)
```
- `from` : starting date (required)
- `to`   : end date (optional)
- `by`   : increment — `"day"`, `"week"`, `"month"`, `"quarter"`, or `"year"`
- `length.out` : desired length of the sequence

**Sequence of first day of each year**

In [ ]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

**Sequence of days**

In [ ]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

**Sequence of months**

In [ ]:
seq(as.Date("2017-01-01"), by = "months", length = 6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

**Sequence by years (using `length`)**

In [ ]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

**Sequence with defined start and end dates, going backwards by month**

In [ ]:
startdate = as.Date("2016-1-1")
enddate   = as.Date("2017-1-1")
out = seq(enddate, startdate, by = "-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

### 2.2 Generating sequences of alphabets

`letters` — sequence of lowercase alphabets

In [ ]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

`letters[from_index:to_index]` — a specific range of lowercase alphabets

In [ ]:
letters[1:3]
letters[3:1]
letters[21:23]
letters[2]

[1] "a" "b" "c"

[1] "c" "b" "a"

[1] "u" "v" "w"

[1] "b"

`LETTERS` — sequence of uppercase alphabets

In [ ]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

`LETTERS[from_index:to_index]` — a specific range of uppercase alphabets

In [ ]:
LETTERS[1:3]
LETTERS[3:1]
LETTERS[21:23]
LETTERS[2]

[1] "A" "B" "C"

[1] "C" "B" "A"

[1] "U" "V" "W"

[1] "B"

## Lecture 28 — Repeats

The `rep()` function replicates the values of a vector a specified number of times.

```
rep(x)                # replicate values of x
rep(x, times = n)     # repeat x as a whole n times
rep(x, each = n)      # repeat each element n times
rep(x, length.out = n)  # or rep(x, length = n) / rep_len(x, length.out)
```

In [ ]:
help("rep")

### 3.1 Repeat an object n times

In [ ]:
rep(3.5, times = 10)
rep(1:4, 2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

### 3.2 Repeat an object n times vs repeat each cell n times

In [ ]:
x = 1:4
x

rep(x, times = 3)
rep(x, each = 3)

[1] 1 2 3 4

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

### 3.3 Combining `each` and `times` — order matters!

In [ ]:
rep(1:4, each = 2)
rep(1:4, each = 2, times = 3)
rep(1:4, times = 3, each = 2)

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

### 3.4 Repeating each element a different number of times

In [ ]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [ ]:
ans = seq(from = 2, to = 8, by = 2)
ans

rep(1:4, ans)

[1] 2 4 6 8

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

### 3.5 Repeating a matrix

In [ ]:
x = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = T)
x

rep(x, 3)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

### 3.6 Repetition of characters

In [ ]:
rep(c("a", "b", "c"), 2)
rep(c("apple", "banana", "cake"), 2)

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

### 3.7 Repetition of characters for a pre-specified length

In [ ]:
rep(2, length.out = 5)
rep(2, length = 5)
rep(c(2,3), length = 5)
rep(c(2,3,4), length = 5)

[1] 2 2 2 2 2

[1] 2 2 2 2 2

[1] 2 3 2 3 2

[1] 2 3 4 2 3

In [ ]:
rep("apple", length = 5)
rep(c("a", "b", "c"), length = 2)
rep(c("a", "b", "c"), length = 5)

[1] "apple" "apple" "apple" "apple" "apple"

[1] "a" "b"

[1] "a" "b" "c" "a" "b"

## Lecture 29 — Sorting, Ordering and Mode

### 4.1 `sort()`
`sort()` arranges the values of a vector in ascending order (default) or descending order.

```
sort(x, decreasing = FALSE, ...)
sort(x, decreasing = FALSE, na.last = NA, ...)
```

In [ ]:
y = c(8,5,7,6)
y

sort(y)
sort(y, decreasing = TRUE)

[1] 8 5 7 6

[1] 5 6 7 8

[1] 8 7 6 5

### 4.2 `order()`
`order()` returns the *positions* that would arrange the vector in sorted order — i.e. it sorts according to the index.

```
order(x, decreasing = FALSE, ...)
order(x, decreasing = FALSE, na.last = TRUE, ...)
```

In [ ]:
y = c(9,8,5,7,6)
y

order(y)
order(y, decreasing = TRUE)

[1] 9 8 5 7 6

[1] 3 5 4 2 1

[1] 1 2 4 5 3

### 4.3 `mode()`
Every object has a **mode**, which indicates how it is stored in memory (number, character string, list, function, etc.).

In [ ]:
mode(2.432)
mode(c(3,4,5,6,7,8))
mode("India")
mode(c("India", "CANADA"))

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

In [ ]:
mode(factor(c("UP", "MP")))
mode(list("India", "USA"))
mode(data.frame(x = 1:2, y = c("India", "USA")))
mode(print)

[1] "numeric"

[1] "list"

[1] "list"

[1] "function"

## Lecture 30 — Lists

Unlike vectors, matrices, and arrays (which can hold only **one type of data**), a **list** can hold elements of **different types/modes**.

- Lists can be indexed by position: `x[[5]]`
- Lists can extract sublists: `x[c(2,5)]`
- List elements can have names: `x[["Students"]]` or `x$Students`

### 5.1 Arithmetic on matrices (for comparison)

In [ ]:
x1 = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = T)
x2 = matrix(nrow = 2, ncol = 2, data = 5:8, byrow = T)
x1
x2

x1 + x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

### 5.2 Why lists are needed — mixing types breaks matrix arithmetic

In [ ]:
x1[2,1] = "hello"
x1

# This will now throw an error, since x1 has become a character matrix
tryCatch(
  x1 + x2,
  error = function(e) print(e)
)

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

<simpleError in x1 + x2: non-numeric argument to binary operator>

### 5.3 Lists can contain matrices as objects

In [ ]:
x1 = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = T)
x2 = matrix(nrow = 2, ncol = 2, data = 5:8, byrow = T)

matlist = list(x1, x2)
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### 5.4 `[ ]` vs `[[ ]]` indexing on lists

In [ ]:
matlist[1]
matlist[2]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### 5.5 Lists containing different object types

In [ ]:
z1 = list(
  c("water", "juice", "lemonade"),
  rep(1:4, each = 2),
  matrix(data = 5:8, nrow = 2, ncol = 2, byrow = T)
)
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### 5.6 Accessing elements within a list — `[ ]` vs `[[ ]]`

In [ ]:
z1[[1]]        # the first list element (a character vector)

z1[1][2]       # WRONG: [1] gives a sub-list of length 1; [2] on that is out of range -> NULL

z1[[1]][2]     # CORRECT: [[1]] extracts the vector itself, [2] then indexes into it

[1] "water"    "juice"    "lemonade"

[[1]]
NULL

[1] "juice"

## Summary

| Concept | Key function(s) |
|---|---|
| Numeric sequences | `:`, `seq()` |
| Index vectors | `seq(along = x)` |
| Date sequences | `seq(as.Date(...), by = "days"/"months"/"years", ...)` |
| Alphabet sequences | `letters`, `LETTERS` |
| Repeats | `rep(x, times=)`, `rep(x, each=)` |
| Sorting | `sort()` |
| Ordering (indices) | `order()` |
| Object storage type | `mode()` |
| Mixed-type containers | `list()`, `[ ]`, `[[ ]]` |

*Notebook prepared from NPTEL "Foundations of R Software" — Lectures 26–30, Prof. Shalabh, IIT Kanpur.*